/**
 * Express.js Integration Example
 * 
 * This example demonstrates how to integrate the UEP Protocol Definition System
 * with an Express.js application, including validation middleware, client generation,
 * and automated API documentation serving.
 */

import express, { Request, Response, NextFunction } from 'express';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';

import { ProtocolSchemaRepository } from '../ProtocolSchemaRepository';
import { ProtocolCompiler } from '../ProtocolCompiler';
import { ProtocolDocumentationGenerator } from '../ProtocolDocumentationGenerator';

// Example: Using generated types and validators
// These would be generated by the Protocol Compiler
interface User {
  id: string;
  email: string;
  name?: string;
  createdAt: string;
  updatedAt: string;
}

interface CreateUserRequest {
  email: string;
  name?: string;
}

interface UserList {
  users: User[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Mock validation functions (would be generated)
function validateCreateUserRequest(data: any): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  if (!data.email) {
    errors.push('Email is required');
  } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
    errors.push('Invalid email format');
  }
  
  return { valid: errors.length === 0, errors };
}

function validateUser(data: any): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  if (!data.id) errors.push('ID is required');
  if (!data.email) errors.push('Email is required');
  if (!data.createdAt) errors.push('CreatedAt is required');
  if (!data.updatedAt) errors.push('UpdatedAt is required');
  
  return { valid: errors.length === 0, errors };
}

/**
 * UEP Protocol Express Integration Class
 */
export class UEPExpressApp {
  private app: express.Application;
  private repository: ProtocolSchemaRepository;
  private compiler: ProtocolCompiler;
  private docGenerator: ProtocolDocumentationGenerator;
  
  // Mock user data store
  private users: User[] = [
    {
      id: '1',
      email: 'john@example.com',
      name: 'John Doe',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: '2',
      email: 'jane@example.com',
      name: 'Jane Smith',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  constructor() {
    this.app = express();
    this.initializeUEPComponents();
    this.setupMiddleware();
    this.setupRoutes();
    this.setupUEPIntegration();
  }

  private initializeUEPComponents(): void {
    // Initialize Protocol Schema Repository
    this.repository = new ProtocolSchemaRepository({
      basePath: './protocols',
      gitEnabled: false,
      validationEnabled: true,
      autoVersioning: false,
      backupEnabled: false,
      compressionEnabled: false,
      cachingEnabled: true,
      indexingEnabled: true
    });

    // Initialize Protocol Compiler
    this.compiler = new ProtocolCompiler({
      outputPath: './generated',
      typescript: {
        target: 'es2020',
        module: 'commonjs',
        strict: true
      },
      validation: {
        generateInterfaces: true,
        generateValidators: true,
        generateUtilities: true
      }
    });

    // Initialize Documentation Generator
    this.docGenerator = new ProtocolDocumentationGenerator({
      outputPath: './docs',
      formats: [
        { type: 'html', filename: 'index.html' },
        { type: 'openapi-ui', filename: 'api-docs.html' },
        { type: 'redoc', filename: 'redoc.html' }
      ],
      theme: 'default',
      includeExamples: true,
      includeDiagrams: true,
      includeInteractive: true,
      generateTOC: true,
      enableSearch: true,
      branding: {
        title: 'User Service API',
        description: 'RESTful API for user management',
        primaryColor: '#007acc',
        secondaryColor: '#0056b3',
        fontFamily: 'Arial, sans-serif',
        organization: 'Example Corp',
        contact: {
          name: 'API Team',
          email: 'api@example.com'
        }
      },
      templates: {
        templatePath: './templates',
        customTemplates: new Map(),
        helpers: new Map(),
        partials: new Map()
      }
    });
  }

  private setupMiddleware(): void {
    // Security middleware
    this.app.use(helmet());
    this.app.use(cors({
      origin: process.env.ALLOWED_ORIGINS?.split(',') || ['http://localhost:3000'],
      credentials: true
    }));

    // Rate limiting
    const limiter = rateLimit({
      windowMs: 15 * 60 * 1000, // 15 minutes
      max: 100, // limit each IP to 100 requests per windowMs
      message: 'Too many requests from this IP, please try again later.'
    });
    this.app.use('/api/', limiter);

    // Body parsing
    this.app.use(express.json({ limit: '10mb' }));
    this.app.use(express.urlencoded({ extended: true }));

    // UEP Protocol headers middleware
    this.app.use('/api/', this.uepProtocolMiddleware());

    // Request logging
    this.app.use(this.requestLogger());

    // Error handling
    this.app.use(this.errorHandler());
  }

  private setupRoutes(): void {
    // Health check endpoint
    this.app.get('/health', (req, res) => {
      res.json({
        status: 'healthy',
        timestamp: new Date().toISOString(),
        version: process.env.API_VERSION || '1.0.0'
      });
    });

    // API routes with UEP protocol validation
    this.setupUserRoutes();
    this.setupProtocolManagementRoutes();
    this.setupDocumentationRoutes();
  }

  private setupUserRoutes(): void {
    const router = express.Router();

    // GET /api/users - List users with pagination
    router.get('/users', this.validateQuery(['page', 'limit']), (req: Request, res: Response) => {
      const page = parseInt(req.query.page as string) || 1;
      const limit = parseInt(req.query.limit as string) || 20;
      const offset = (page - 1) * limit;

      const paginatedUsers = this.users.slice(offset, offset + limit);
      const total = this.users.length;

      const response: UserList = {
        users: paginatedUsers,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.ceil(total / limit)
        }
      };

      res.json(response);
    });

    // GET /api/users/:id - Get user by ID
    router.get('/users/:id', (req: Request, res: Response) => {
      const user = this.users.find(u => u.id === req.params.id);
      
      if (!user) {
        return res.status(404).json({
          error: 'User not found',
          code: 'USER_NOT_FOUND'
        });
      }

      res.json(user);
    });

    // POST /api/users - Create new user
    router.post('/users', this.validateBody(validateCreateUserRequest), (req: Request, res: Response) => {
      const userData: CreateUserRequest = req.body;
      
      // Check for duplicate email
      const existingUser = this.users.find(u => u.email === userData.email);
      if (existingUser) {
        return res.status(409).json({
          error: 'User with this email already exists',
          code: 'DUPLICATE_EMAIL'
        });
      }

      const newUser: User = {
        id: (this.users.length + 1).toString(),
        email: userData.email,
        name: userData.name,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      this.users.push(newUser);
      res.status(201).json(newUser);
    });

    // PUT /api/users/:id - Update user
    router.put('/users/:id', this.validateBody(validateCreateUserRequest), (req: Request, res: Response) => {
      const userIndex = this.users.findIndex(u => u.id === req.params.id);
      
      if (userIndex === -1) {
        return res.status(404).json({
          error: 'User not found',
          code: 'USER_NOT_FOUND'
        });
      }

      const userData: CreateUserRequest = req.body;
      const updatedUser: User = {
        ...this.users[userIndex],
        email: userData.email,
        name: userData.name,
        updatedAt: new Date().toISOString()
      };

      this.users[userIndex] = updatedUser;
      res.json(updatedUser);
    });

    // DELETE /api/users/:id - Delete user
    router.delete('/users/:id', (req: Request, res: Response) => {
      const userIndex = this.users.findIndex(u => u.id === req.params.id);
      
      if (userIndex === -1) {
        return res.status(404).json({
          error: 'User not found',
          code: 'USER_NOT_FOUND'
        });
      }

      this.users.splice(userIndex, 1);
      res.status(204).send();
    });

    this.app.use('/api', router);
  }

  private setupProtocolManagementRoutes(): void {
    const router = express.Router();

    // GET /protocol/schemas - List all protocol schemas
    router.get('/schemas', async (req: Request, res: Response) => {
      try {
        const protocols = await this.repository.listProtocols();
        res.json({
          protocols: protocols.map(p => ({
            id: p.id,
            name: p.name,
            version: p.version,
            status: p.metadata.status,
            lastUpdated: p.metadata.lastUpdated
          }))
        });
      } catch (error) {
        res.status(500).json({
          error: 'Failed to retrieve protocol schemas',
          code: 'PROTOCOL_RETRIEVAL_ERROR'
        });
      }
    });

    // GET /protocol/schemas/:id - Get specific protocol schema
    router.get('/schemas/:id', async (req: Request, res: Response) => {
      try {
        const protocol = await this.repository.getProtocol(req.params.id);
        if (!protocol) {
          return res.status(404).json({
            error: 'Protocol not found',
            code: 'PROTOCOL_NOT_FOUND'
          });
        }
        res.json(protocol);
      } catch (error) {
        res.status(500).json({
          error: 'Failed to retrieve protocol schema',
          code: 'PROTOCOL_RETRIEVAL_ERROR'
        });
      }
    });

    // POST /protocol/compile/:id - Compile protocol to TypeScript
    router.post('/compile/:id', async (req: Request, res: Response) => {
      try {
        const protocol = await this.repository.getProtocol(req.params.id);
        if (!protocol) {
          return res.status(404).json({
            error: 'Protocol not found',
            code: 'PROTOCOL_NOT_FOUND'
          });
        }

        const result = await this.compiler.compile(protocol);
        res.json({
          success: result.success,
          generatedFiles: result.generatedFiles,
          errors: result.errors
        });
      } catch (error) {
        res.status(500).json({
          error: 'Compilation failed',
          code: 'COMPILATION_ERROR'
        });
      }
    });

    // POST /protocol/docs/:id - Generate documentation
    router.post('/docs/:id', async (req: Request, res: Response) => {
      try {
        const protocol = await this.repository.getProtocol(req.params.id);
        if (!protocol) {
          return res.status(404).json({
            error: 'Protocol not found',
            code: 'PROTOCOL_NOT_FOUND'
          });
        }

        const result = await this.docGenerator.generateDocumentation(protocol);
        res.json({
          success: result.success,
          generatedFiles: result.generatedFiles,
          errors: result.errors
        });
      } catch (error) {
        res.status(500).json({
          error: 'Documentation generation failed',
          code: 'DOCUMENTATION_ERROR'
        });
      }
    });

    this.app.use('/protocol', router);
  }

  private setupDocumentationRoutes(): void {
    // Serve generated documentation
    this.app.use('/docs', express.static('./docs'));
    
    // Redirect root docs to index
    this.app.get('/docs', (req, res) => {
      res.redirect('/docs/index.html');
    });

    // API documentation endpoints
    this.app.get('/api-docs', (req, res) => {
      res.redirect('/docs/api-docs.html');
    });

    this.app.get('/redoc', (req, res) => {
      res.redirect('/docs/redoc.html');
    });
  }

  private setupUEPIntegration(): void {
    // Auto-compile protocols on startup
    this.compileProtocolsOnStartup();

    // Auto-generate documentation on startup
    this.generateDocumentationOnStartup();

    // Set up protocol validation endpoint
    this.app.post('/validate-protocol', async (req: Request, res: Response) => {
      try {
        const validation = await this.repository.validateProtocol(req.body);
        res.json(validation);
      } catch (error) {
        res.status(400).json({
          valid: false,
          errors: [error.message]
        });
      }
    });
  }

  /**
   * Middleware Functions
   */
  private uepProtocolMiddleware(): (req: Request, res: Response, next: NextFunction) => void {
    return (req: Request, res: Response, next: NextFunction) => {
      // Add UEP protocol headers
      res.setHeader('X-UEP-Protocol-Version', '1.0.0');
      res.setHeader('X-UEP-Service-Name', 'user-service');
      res.setHeader('X-UEP-Service-Version', process.env.SERVICE_VERSION || '1.0.0');

      // Validate UEP protocol headers in requests
      const clientProtocolVersion = req.headers['x-uep-protocol-version'];
      if (clientProtocolVersion && clientProtocolVersion !== '1.0.0') {
        return res.status(400).json({
          error: 'Unsupported UEP protocol version',
          code: 'PROTOCOL_VERSION_MISMATCH',
          supported: '1.0.0',
          received: clientProtocolVersion
        });
      }

      next();
    };
  }

  private requestLogger(): (req: Request, res: Response, next: NextFunction) => void {
    return (req: Request, res: Response, next: NextFunction) => {
      const start = Date.now();
      
      res.on('finish', () => {
        const duration = Date.now() - start;
        console.log(`${req.method} ${req.url} - ${res.statusCode} - ${duration}ms`);
      });

      next();
    };
  }

  private validateBody(validator: (data: any) => { valid: boolean; errors: string[] }): 
    (req: Request, res: Response, next: NextFunction) => void {
    return (req: Request, res: Response, next: NextFunction) => {
      const validation = validator(req.body);
      
      if (!validation.valid) {
        return res.status(400).json({
          error: 'Validation failed',
          code: 'VALIDATION_ERROR',
          details: validation.errors
        });
      }

      next();
    };
  }

  private validateQuery(allowedParams: string[]): 
    (req: Request, res: Response, next: NextFunction) => void {
    return (req: Request, res: Response, next: NextFunction) => {
      const errors: string[] = [];

      // Validate query parameters
      for (const [key, value] of Object.entries(req.query)) {
        if (!allowedParams.includes(key)) {
          errors.push(`Unknown query parameter: ${key}`);
        }
      }

      if (req.query.page && (isNaN(Number(req.query.page)) || Number(req.query.page) < 1)) {
        errors.push('Page must be a positive integer');
      }

      if (req.query.limit && (isNaN(Number(req.query.limit)) || Number(req.query.limit) < 1 || Number(req.query.limit) > 100)) {
        errors.push('Limit must be an integer between 1 and 100');
      }

      if (errors.length > 0) {
        return res.status(400).json({
          error: 'Invalid query parameters',
          code: 'QUERY_VALIDATION_ERROR',
          details: errors
        });
      }

      next();
    };
  }

  private errorHandler(): (err: Error, req: Request, res: Response, next: NextFunction) => void {
    return (err: Error, req: Request, res: Response, next: NextFunction) => {
      console.error('Unhandled error:', err);

      if (err.name === 'ValidationError') {
        return res.status(400).json({
          error: 'Validation error',
          code: 'VALIDATION_ERROR',
          message: err.message
        });
      }

      if (err.name === 'SyntaxError' && 'body' in err) {
        return res.status(400).json({
          error: 'Invalid JSON',
          code: 'INVALID_JSON',
          message: 'Request body contains invalid JSON'
        });
      }

      res.status(500).json({
        error: 'Internal server error',
        code: 'INTERNAL_ERROR',
        message: process.env.NODE_ENV === 'development' ? err.message : 'Something went wrong'
      });
    };
  }

  /**
   * Startup Functions
   */
  private async compileProtocolsOnStartup(): Promise<void> {
    try {
      console.log('🔨 Compiling protocols on startup...');
      const protocols = await this.repository.listProtocols();
      
      if (protocols.length === 0) {
        console.log('No protocols found to compile');
        return;
      }

      const results = await this.compiler.batchCompile(protocols);
      
      let successCount = 0;
      let failureCount = 0;

      for (const [protocolId, result] of results) {
        if (result.success) {
          successCount++;
          console.log(`✅ ${protocolId} compiled successfully`);
        } else {
          failureCount++;
          console.error(`❌ ${protocolId} compilation failed:`, result.errors);
        }
      }

      console.log(`📊 Compilation summary: ${successCount} successful, ${failureCount} failed`);
    } catch (error) {
      console.error('Failed to compile protocols on startup:', error.message);
    }
  }

  private async generateDocumentationOnStartup(): Promise<void> {
    try {
      console.log('📄 Generating documentation on startup...');
      const protocols = await this.repository.listProtocols();
      
      if (protocols.length === 0) {
        console.log('No protocols found for documentation');
        return;
      }

      const results = await this.docGenerator.generateBatchDocumentation(protocols);
      
      let successCount = 0;
      let failureCount = 0;

      for (const [protocolId, result] of results) {
        if (result.success) {
          successCount++;
          console.log(`✅ ${protocolId} documentation generated`);
        } else {
          failureCount++;
          console.error(`❌ ${protocolId} documentation failed:`, result.errors);
        }
      }

      console.log(`📊 Documentation summary: ${successCount} successful, ${failureCount} failed`);
      console.log('📚 Documentation available at http://localhost:3000/docs');
    } catch (error) {
      console.error('Failed to generate documentation on startup:', error.message);
    }
  }

  /**
   * Start the server
   */
  public start(port: number = 3000): void {
    this.app.listen(port, () => {
      console.log(`🚀 UEP Express Server running on port ${port}`);
      console.log(`📖 API Documentation: http://localhost:${port}/docs`);
      console.log(`🔧 API Explorer: http://localhost:${port}/api-docs`);
      console.log(`📋 Health Check: http://localhost:${port}/health`);
    });
  }

  /**
   * Get the Express app instance
   */
  public getApp(): express.Application {
    return this.app;
  }
}

/**
 * Example usage
 */
if (require.main === module) {
  const app = new UEPExpressApp();
  app.start(3000);
}

export default UEPExpressApp;