/**
 * React Client Integration Example
 * 
 * This example demonstrates how to integrate UEP protocol definitions
 * with a React application, including type-safe API clients,
 * hooks for data fetching, and validation utilities.
 */

import React, { useState, useEffect, useCallback, createContext, useContext } from 'react';
import axios, { AxiosInstance, AxiosError } from 'axios';

// Generated types (would be generated by Protocol Compiler)
interface User {
  id: string;
  email: string;
  name?: string;
  createdAt: string;
  updatedAt: string;
}

interface CreateUserRequest {
  email: string;
  name?: string;
}

interface UpdateUserRequest {
  email: string;
  name?: string;
}

interface UserList {
  users: User[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

interface PaginationParams {
  page?: number;
  limit?: number;
}

interface ApiResponse<T> {
  data: T;
  success: boolean;
  message?: string;
}

interface ApiError {
  error: string;
  code: string;
  details?: string[];
}

/**
 * UEP Protocol API Client
 */
export class UEPApiClient {
  private axiosInstance: AxiosInstance;
  private baseURL: string;
  private protocolVersion: string;

  constructor(baseURL: string = '/api', protocolVersion: string = '1.0.0') {
    this.baseURL = baseURL;
    this.protocolVersion = protocolVersion;

    this.axiosInstance = axios.create({
      baseURL,
      timeout: 10000,
      headers: {
        'Content-Type': 'application/json',
        'X-UEP-Protocol-Version': protocolVersion,
      },
    });

    this.setupInterceptors();
  }

  private setupInterceptors(): void {
    // Request interceptor
    this.axiosInstance.interceptors.request.use(
      (config) => {
        // Add authentication token if available
        const token = localStorage.getItem('authToken');
        if (token) {
          config.headers.Authorization = `Bearer ${token}`;
        }

        // Add request ID for tracking
        config.headers['X-Request-ID'] = this.generateRequestId();

        console.log(`[UEP API] ${config.method?.toUpperCase()} ${config.url}`);
        return config;
      },
      (error) => {
        console.error('[UEP API] Request error:', error);
        return Promise.reject(error);
      }
    );

    // Response interceptor
    this.axiosInstance.interceptors.response.use(
      (response) => {
        // Check UEP protocol headers
        const serverVersion = response.headers['x-uep-protocol-version'];
        if (serverVersion && serverVersion !== this.protocolVersion) {
          console.warn(
            `[UEP API] Protocol version mismatch: Client ${this.protocolVersion}, Server ${serverVersion}`
          );
        }

        console.log(`[UEP API] Response ${response.status} - ${response.config.url}`);
        return response;
      },
      (error: AxiosError<ApiError>) => {
        const apiError = this.handleApiError(error);
        console.error('[UEP API] Response error:', apiError);
        return Promise.reject(apiError);
      }
    );
  }

  private generateRequestId(): string {
    return `req_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private handleApiError(error: AxiosError<ApiError>): ApiError {
    if (error.response?.data) {
      return error.response.data;
    }

    if (error.code === 'ECONNABORTED') {
      return {
        error: 'Request timeout',
        code: 'TIMEOUT_ERROR',
      };
    }

    if (error.code === 'NETWORK_ERROR') {
      return {
        error: 'Network error',
        code: 'NETWORK_ERROR',
      };
    }

    return {
      error: error.message || 'Unknown error',
      code: 'UNKNOWN_ERROR',
    };
  }

  // User API methods
  async listUsers(params: PaginationParams = {}): Promise<UserList> {
    const response = await this.axiosInstance.get<UserList>('/users', { params });
    return response.data;
  }

  async getUser(id: string): Promise<User> {
    const response = await this.axiosInstance.get<User>(`/users/${id}`);
    return response.data;
  }

  async createUser(userData: CreateUserRequest): Promise<User> {
    const response = await this.axiosInstance.post<User>('/users', userData);
    return response.data;
  }

  async updateUser(id: string, userData: UpdateUserRequest): Promise<User> {
    const response = await this.axiosInstance.put<User>(`/users/${id}`, userData);
    return response.data;
  }

  async deleteUser(id: string): Promise<void> {
    await this.axiosInstance.delete(`/users/${id}`);
  }

  // Health check
  async healthCheck(): Promise<{ status: string; timestamp: string; version: string }> {
    const response = await this.axiosInstance.get('/health');
    return response.data;
  }
}

/**
 * React Context for UEP API Client
 */
interface UEPApiContextType {
  client: UEPApiClient;
  isOnline: boolean;
}

const UEPApiContext = createContext<UEPApiContextType | null>(null);

export const UEPApiProvider: React.FC<{ 
  children: React.ReactNode;
  baseURL?: string;
  protocolVersion?: string;
}> = ({ children, baseURL, protocolVersion }) => {
  const [client] = useState(() => new UEPApiClient(baseURL, protocolVersion));
  const [isOnline, setIsOnline] = useState(navigator.onLine);

  useEffect(() => {
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  return (
    <UEPApiContext.Provider value={{ client, isOnline }}>
      {children}
    </UEPApiContext.Provider>
  );
};

export const useUEPApi = (): UEPApiContextType => {
  const context = useContext(UEPApiContext);
  if (!context) {
    throw new Error('useUEPApi must be used within UEPApiProvider');
  }
  return context;
};

/**
 * Custom Hooks for Data Fetching
 */
export const useUsers = (params: PaginationParams = {}) => {
  const { client } = useUEPApi();
  const [data, setData] = useState<UserList | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<ApiError | null>(null);

  const fetchUsers = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const result = await client.listUsers(params);
      setData(result);
    } catch (err) {
      setError(err as ApiError);
    } finally {
      setLoading(false);
    }
  }, [client, JSON.stringify(params)]);

  useEffect(() => {
    fetchUsers();
  }, [fetchUsers]);

  return {
    data,
    loading,
    error,
    refetch: fetchUsers,
  };
};

export const useUser = (id: string | null) => {
  const { client } = useUEPApi();
  const [data, setData] = useState<User | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);

  const fetchUser = useCallback(async () => {
    if (!id) return;
    
    try {
      setLoading(true);
      setError(null);
      const result = await client.getUser(id);
      setData(result);
    } catch (err) {
      setError(err as ApiError);
    } finally {
      setLoading(false);
    }
  }, [client, id]);

  useEffect(() => {
    fetchUser();
  }, [fetchUser]);

  return {
    data,
    loading,
    error,
    refetch: fetchUser,
  };
};

export const useUserMutations = () => {
  const { client } = useUEPApi();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);

  const createUser = async (userData: CreateUserRequest): Promise<User | null> => {
    try {
      setLoading(true);
      setError(null);
      const result = await client.createUser(userData);
      return result;
    } catch (err) {
      setError(err as ApiError);
      return null;
    } finally {
      setLoading(false);
    }
  };

  const updateUser = async (id: string, userData: UpdateUserRequest): Promise<User | null> => {
    try {
      setLoading(true);
      setError(null);
      const result = await client.updateUser(id, userData);
      return result;
    } catch (err) {
      setError(err as ApiError);
      return null;
    } finally {
      setLoading(false);
    }
  };

  const deleteUser = async (id: string): Promise<boolean> => {
    try {
      setLoading(true);
      setError(null);
      await client.deleteUser(id);
      return true;
    } catch (err) {
      setError(err as ApiError);
      return false;
    } finally {
      setLoading(false);
    }
  };

  return {
    createUser,
    updateUser,
    deleteUser,
    loading,
    error,
  };
};

/**
 * Validation Utilities (would be generated by Protocol Compiler)
 */
export const validateEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

export const validateCreateUserRequest = (data: Partial<CreateUserRequest>): { 
  valid: boolean; 
  errors: string[]; 
} => {
  const errors: string[] = [];

  if (!data.email) {
    errors.push('Email is required');
  } else if (!validateEmail(data.email)) {
    errors.push('Invalid email format');
  }

  if (data.name && data.name.trim().length < 2) {
    errors.push('Name must be at least 2 characters long');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
};

/**
 * React Components
 */

// Loading Spinner Component
const LoadingSpinner: React.FC = () => (
  <div className="flex justify-center items-center p-4">
    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
  </div>
);

// Error Display Component
const ErrorDisplay: React.FC<{ error: ApiError; onRetry?: () => void }> = ({ 
  error, 
  onRetry 
}) => (
  <div className="bg-red-50 border border-red-200 rounded-md p-4 m-4">
    <div className="flex">
      <div className="flex-shrink-0">
        <svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
          <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
        </svg>
      </div>
      <div className="ml-3">
        <h3 className="text-sm font-medium text-red-800">
          Error ({error.code})
        </h3>
        <div className="mt-2 text-sm text-red-700">
          <p>{error.error}</p>
          {error.details && (
            <ul className="list-disc list-inside mt-1">
              {error.details.map((detail, index) => (
                <li key={index}>{detail}</li>
              ))}
            </ul>
          )}
        </div>
        {onRetry && (
          <div className="mt-3">
            <button
              onClick={onRetry}
              className="bg-red-100 hover:bg-red-200 text-red-800 px-3 py-1 rounded text-sm"
            >
              Retry
            </button>
          </div>
        )}
      </div>
    </div>
  </div>
);

// User List Component
export const UserList: React.FC = () => {
  const [currentPage, setCurrentPage] = useState(1);
  const { data, loading, error, refetch } = useUsers({ page: currentPage, limit: 10 });

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorDisplay error={error} onRetry={refetch} />;
  if (!data) return <div>No data available</div>;

  return (
    <div className="bg-white shadow overflow-hidden sm:rounded-md">
      <ul className="divide-y divide-gray-200">
        {data.users.map((user) => (
          <li key={user.id}>
            <div className="px-4 py-4 sm:px-6">
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <div className="flex-shrink-0 h-10 w-10">
                    <div className="h-10 w-10 rounded-full bg-gray-300 flex items-center justify-center">
                      <span className="text-sm font-medium text-gray-600">
                        {(user.name || user.email).charAt(0).toUpperCase()}
                      </span>
                    </div>
                  </div>
                  <div className="ml-4">
                    <div className="text-sm font-medium text-gray-900">
                      {user.name || 'No name'}
                    </div>
                    <div className="text-sm text-gray-500">{user.email}</div>
                  </div>
                </div>
                <div className="text-sm text-gray-500">
                  Created: {new Date(user.createdAt).toLocaleDateString()}
                </div>
              </div>
            </div>
          </li>
        ))}
      </ul>

      {/* Pagination */}
      {data.pagination.totalPages > 1 && (
        <div className="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
          <div className="flex-1 flex justify-between sm:hidden">
            <button
              onClick={() => setCurrentPage(Math.max(1, currentPage - 1))}
              disabled={currentPage === 1}
              className="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"
            >
              Previous
            </button>
            <button
              onClick={() => setCurrentPage(Math.min(data.pagination.totalPages, currentPage + 1))}
              disabled={currentPage === data.pagination.totalPages}
              className="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"
            >
              Next
            </button>
          </div>
          <div className="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
            <div>
              <p className="text-sm text-gray-700">
                Showing page <span className="font-medium">{currentPage}</span> of{' '}
                <span className="font-medium">{data.pagination.totalPages}</span>
              </p>
            </div>
            <div>
              <nav className="relative z-0 inline-flex rounded-md shadow-sm -space-x-px">
                {Array.from({ length: data.pagination.totalPages }, (_, i) => i + 1).map((page) => (
                  <button
                    key={page}
                    onClick={() => setCurrentPage(page)}
                    className={`relative inline-flex items-center px-4 py-2 border text-sm font-medium ${
                      page === currentPage
                        ? 'z-10 bg-blue-50 border-blue-500 text-blue-600'
                        : 'bg-white border-gray-300 text-gray-500 hover:bg-gray-50'
                    }`}
                  >
                    {page}
                  </button>
                ))}
              </nav>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// Create User Form Component
export const CreateUserForm: React.FC<{ onSuccess?: (user: User) => void }> = ({ 
  onSuccess 
}) => {
  const [formData, setFormData] = useState<CreateUserRequest>({ email: '', name: '' });
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  const { createUser, loading, error } = useUserMutations();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Client-side validation
    const validation = validateCreateUserRequest(formData);
    if (!validation.valid) {
      setValidationErrors(validation.errors);
      return;
    }

    setValidationErrors([]);
    const result = await createUser(formData);
    
    if (result) {
      setFormData({ email: '', name: '' });
      onSuccess?.(result);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    
    // Clear validation errors when user starts typing
    if (validationErrors.length > 0) {
      setValidationErrors([]);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 bg-white p-6 rounded-lg shadow">
      <h3 className="text-lg font-medium text-gray-900">Create New User</h3>
      
      {(validationErrors.length > 0 || error) && (
        <div className="bg-red-50 border border-red-200 rounded-md p-3">
          {validationErrors.map((err, index) => (
            <p key={index} className="text-sm text-red-600">{err}</p>
          ))}
          {error && <p className="text-sm text-red-600">{error.error}</p>}
        </div>
      )}

      <div>
        <label htmlFor="email" className="block text-sm font-medium text-gray-700">
          Email *
        </label>
        <input
          type="email"
          id="email"
          name="email"
          value={formData.email}
          onChange={handleChange}
          required
          className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
        />
      </div>

      <div>
        <label htmlFor="name" className="block text-sm font-medium text-gray-700">
          Name
        </label>
        <input
          type="text"
          id="name"
          name="name"
          value={formData.name || ''}
          onChange={handleChange}
          className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
        />
      </div>

      <button
        type="submit"
        disabled={loading}
        className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50"
      >
        {loading ? 'Creating...' : 'Create User'}
      </button>
    </form>
  );
};

// User Detail Component
export const UserDetail: React.FC<{ userId: string }> = ({ userId }) => {
  const { data: user, loading, error, refetch } = useUser(userId);
  const { deleteUser } = useUserMutations();
  const [isDeleting, setIsDeleting] = useState(false);

  const handleDelete = async () => {
    if (!window.confirm('Are you sure you want to delete this user?')) {
      return;
    }

    setIsDeleting(true);
    const success = await deleteUser(userId);
    
    if (success) {
      // Navigate back or update parent component
      console.log('User deleted successfully');
    }
    
    setIsDeleting(false);
  };

  if (loading) return <LoadingSpinner />;
  if (error) return <ErrorDisplay error={error} onRetry={refetch} />;
  if (!user) return <div>User not found</div>;

  return (
    <div className="bg-white shadow overflow-hidden sm:rounded-lg">
      <div className="px-4 py-5 sm:px-6">
        <h3 className="text-lg leading-6 font-medium text-gray-900">
          User Information
        </h3>
        <p className="mt-1 max-w-2xl text-sm text-gray-500">
          Personal details and information.
        </p>
      </div>
      <div className="border-t border-gray-200">
        <dl>
          <div className="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt className="text-sm font-medium text-gray-500">User ID</dt>
            <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{user.id}</dd>
          </div>
          <div className="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt className="text-sm font-medium text-gray-500">Email</dt>
            <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{user.email}</dd>
          </div>
          <div className="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt className="text-sm font-medium text-gray-500">Name</dt>
            <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
              {user.name || 'Not provided'}
            </dd>
          </div>
          <div className="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt className="text-sm font-medium text-gray-500">Created</dt>
            <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
              {new Date(user.createdAt).toLocaleString()}
            </dd>
          </div>
          <div className="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt className="text-sm font-medium text-gray-500">Last Updated</dt>
            <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
              {new Date(user.updatedAt).toLocaleString()}
            </dd>
          </div>
        </dl>
      </div>
      <div className="px-4 py-3 bg-gray-50 text-right sm:px-6">
        <button
          onClick={handleDelete}
          disabled={isDeleting}
          className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:opacity-50"
        >
          {isDeleting ? 'Deleting...' : 'Delete User'}
        </button>
      </div>
    </div>
  );
};

// Main App Component Example
export const UserManagementApp: React.FC = () => {
  const [selectedUserId, setSelectedUserId] = useState<string | null>(null);
  const [showCreateForm, setShowCreateForm] = useState(false);

  const handleUserCreated = (user: User) => {
    setShowCreateForm(false);
    // Optionally select the newly created user
    setSelectedUserId(user.id);
  };

  return (
    <UEPApiProvider baseURL="/api" protocolVersion="1.0.0">
      <div className="min-h-screen bg-gray-100">
        <div className="py-6">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold text-gray-900">User Management</h1>
          </div>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="py-4">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
                {/* User List */}
                <div className="lg:col-span-2">
                  <div className="mb-4">
                    <button
                      onClick={() => setShowCreateForm(!showCreateForm)}
                      className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md text-sm font-medium"
                    >
                      {showCreateForm ? 'Cancel' : 'Create User'}
                    </button>
                  </div>
                  
                  {showCreateForm && (
                    <div className="mb-6">
                      <CreateUserForm onSuccess={handleUserCreated} />
                    </div>
                  )}
                  
                  <UserList />
                </div>

                {/* User Detail */}
                <div className="lg:col-span-1">
                  {selectedUserId ? (
                    <UserDetail userId={selectedUserId} />
                  ) : (
                    <div className="bg-white p-6 rounded-lg shadow text-center text-gray-500">
                      Select a user to view details
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </UEPApiProvider>
  );
};

export default UserManagementApp;