#!/bin/bash

# All-Purpose Meta-Agent Factory - Startup Script
# Comprehensive Docker Compose orchestration with health checks and validation

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_FILE="$PROJECT_ROOT/logs/startup.log"
ENVIRONMENT="${1:-development}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging function
log() {
    echo -e "${2:-$GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}" | tee -a "$LOG_FILE"
}

error() {
    log "$1" "$RED"
    exit 1
}

warn() {
    log "$1" "$YELLOW"
}

info() {
    log "$1" "$BLUE"
}

# Create logs directory
mkdir -p "$PROJECT_ROOT/logs"

log "Starting All-Purpose Meta-Agent Factory - Environment: $ENVIRONMENT"

# Change to project root
cd "$PROJECT_ROOT"

# Check prerequisites
info "Checking prerequisites..."

# Check Docker
if ! command -v docker &> /dev/null; then
    error "Docker is not installed or not in PATH"
fi

# Check Docker Compose
if ! command -v docker-compose &> /dev/null; then
    error "Docker Compose is not installed or not in PATH"
fi

# Check for .env file
if [[ ! -f ".env" ]]; then
    warn ".env file not found. Checking for required environment variables..."
    
    if [[ -z "${ANTHROPIC_API_KEY:-}" && -z "${OPENAI_API_KEY:-}" ]]; then
        error "At least one AI API key must be configured (ANTHROPIC_API_KEY or OPENAI_API_KEY)"
    fi
    
    info "Environment variables found. Creating minimal .env file..."
    cat > .env << EOF
# Minimal configuration - generated by startup script
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
NODE_ENV=${ENVIRONMENT}
JWT_SECRET=${JWT_SECRET:-$(openssl rand -hex 32)}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD:-admin}
EOF
fi

# Validate environment file
info "Validating environment configuration..."
source .env

if [[ -z "${ANTHROPIC_API_KEY:-}" && -z "${OPENAI_API_KEY:-}" ]]; then
    error "At least one AI API key must be configured in .env file"
fi

# Determine compose files
COMPOSE_FILES="-f docker-compose.yml"

case "$ENVIRONMENT" in
    "production")
        COMPOSE_FILES="$COMPOSE_FILES -f docker-compose.prod.yml"
        info "Using production configuration"
        ;;
    "development")
        if [[ -f "docker-compose.override.yml" ]]; then
            COMPOSE_FILES="$COMPOSE_FILES -f docker-compose.override.yml"
        fi
        info "Using development configuration with overrides"
        ;;
    *)
        warn "Unknown environment '$ENVIRONMENT', using default configuration"
        ;;
esac

# Create required directories
info "Creating required directories..."
mkdir -p data/{factory-core,domain-agents,uep-service,uep-registry,redis,nats,prometheus,grafana,traefik}
mkdir -p logs/{factory-core,domain-agents,uep-service,uep-registry,nats}

# Set proper permissions
chmod -R 755 data/
chmod -R 755 logs/

# Stop existing containers
info "Stopping any existing containers..."
docker-compose $COMPOSE_FILES down --remove-orphans || true

# Pull latest images
info "Pulling latest images..."
docker-compose $COMPOSE_FILES pull

# Build custom images
info "Building custom images..."
docker-compose $COMPOSE_FILES build --parallel

# Start infrastructure services first
info "Starting infrastructure services..."
docker-compose $COMPOSE_FILES up -d etcd redis nats-broker

# Wait for infrastructure to be healthy
info "Waiting for infrastructure services to be healthy..."
sleep 30

# Check infrastructure health
check_service_health() {
    local service_name=$1
    local max_attempts=12
    local attempt=1
    
    while [[ $attempt -le $max_attempts ]]; do
        if docker-compose $COMPOSE_FILES ps --services --filter "status=running" | grep -q "$service_name"; then
            local health_status=$(docker inspect --format='{{.State.Health.Status}}' "meta-agent-$service_name" 2>/dev/null || echo "unknown")
            if [[ "$health_status" == "healthy" ]] || [[ "$health_status" == "unknown" ]]; then
                log "$service_name is healthy" "$GREEN"
                return 0
            fi
        fi
        
        info "Waiting for $service_name to be healthy (attempt $attempt/$max_attempts)..."
        sleep 10
        ((attempt++))
    done
    
    error "$service_name failed to become healthy within timeout"
}

# Check infrastructure services
for service in etcd redis nats-broker; do
    check_service_health "$service"
done

# Start UEP Registry
info "Starting UEP Registry service..."
docker-compose $COMPOSE_FILES up -d uep-registry
check_service_health "uep-registry"

# Start application services
info "Starting application services..."
docker-compose $COMPOSE_FILES up -d factory-core domain-agents uep-service

# Wait for application services
for service in factory-core domain-agents uep-service; do
    check_service_health "$service"
done

# Start observability and gateway
info "Starting observability and gateway services..."
docker-compose $COMPOSE_FILES up -d observability api-gateway

# Final health check
info "Performing final system health check..."
sleep 15

# Verify all services are running
info "Verifying all services are running..."
docker-compose $COMPOSE_FILES ps

# Test key endpoints
info "Testing key endpoints..."

test_endpoint() {
    local url=$1
    local name=$2
    local max_attempts=6
    local attempt=1
    
    while [[ $attempt -le $max_attempts ]]; do
        if curl -s -f "$url" > /dev/null 2>&1; then
            log "$name endpoint is responding" "$GREEN"
            return 0
        fi
        
        info "Testing $name endpoint (attempt $attempt/$max_attempts)..."
        sleep 10
        ((attempt++))
    done
    
    warn "$name endpoint is not responding at $url"
}

# Test endpoints
test_endpoint "http://localhost:3000/health" "Factory Core"
test_endpoint "http://localhost:3002/health" "Domain Agents"
test_endpoint "http://localhost:3001/health" "UEP Registry"
test_endpoint "http://localhost:3003/health" "UEP Service"
test_endpoint "http://localhost:9090/-/healthy" "Prometheus"
test_endpoint "http://localhost:8080/ping" "Traefik"

# Display success message and access information
log "========================================" "$GREEN"
log "All-Purpose Meta-Agent Factory Started Successfully!" "$GREEN"
log "========================================" "$GREEN"
log ""
log "🌐 Access Points:" "$BLUE"
log "  • Main Dashboard:     http://localhost:3000" 
log "  • Factory Core:       http://localhost:3000"
log "  • Domain Agents:      http://localhost:3002"
log "  • UEP Registry:       http://localhost:3001"
log "  • UEP Service:        http://localhost:3003"
log "  • Observability:      http://localhost:3004 (Grafana)"
log "  • Metrics:            http://localhost:9090 (Prometheus)"
log "  • API Gateway:        http://localhost:8080 (Traefik)"
log ""
log "📊 Monitoring:" "$BLUE"
log "  • Observability Dashboard: http://localhost:3000/admin/observability"
log "  • Grafana (admin/admin):    http://localhost:3004"
log "  • Prometheus:               http://localhost:9090"
log "  • Traefik Dashboard:        http://localhost:8080"
log ""
log "🔧 Management Commands:" "$BLUE"
log "  • View logs:    docker-compose $COMPOSE_FILES logs -f [service]"
log "  • Stop system:  docker-compose $COMPOSE_FILES down"
log "  • Restart:      docker-compose $COMPOSE_FILES restart [service]"
log "  • Scale up:     docker-compose $COMPOSE_FILES up -d --scale factory-core=2"
log ""
log "Environment: $ENVIRONMENT" "$YELLOW"
log "Compose files: $COMPOSE_FILES" "$YELLOW"
log ""
log "✅ All services are running and healthy!" "$GREEN"
log "🚀 Ready to process meta-agent requests!" "$GREEN"