#!/usr/bin/env node

/**
 * Five Document Framework Agent - Main Entry Point
 * 
 * CLI interface for the Five Document Framework Agent
 * Generates and maintains the 5 core documents for systematic project organization
 */

import { FiveDocumentFrameworkAgent } from './core/FiveDocumentFrameworkAgent.js';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs-extra';

// Command line argument parsing
const args = process.argv.slice(2);
const commands = {
  help: args.includes('--help') || args.includes('-h'),
  version: args.includes('--version') || args.includes('-v'),
  init: args.includes('init'),
  generate: args.includes('generate') || args.length === 0,
  validate: args.includes('validate'),
  status: args.includes('status')
};

const options = {
  projectDir: getOptionValue('--project-dir') || process.cwd(),
  outputDir: getOptionValue('--output-dir'),
  templateDir: getOptionValue('--template-dir'),
  validateOnly: args.includes('--validate-only'),
  backupExisting: !args.includes('--no-backup'),
  verbose: args.includes('--verbose') || args.includes('-v'),
  dryRun: args.includes('--dry-run')
};

function getOptionValue(option: string): string | undefined {
  const index = args.indexOf(option);
  return index !== -1 && index + 1 < args.length ? args[index + 1] : undefined;
}

async function main() {
  try {
    // Handle help command
    if (commands.help) {
      showHelp();
      return;
    }

    // Handle version command
    if (commands.version) {
      showVersion();
      return;
    }

    console.log(chalk.blue('📚 Five Document Framework Agent'));
    console.log(chalk.gray('Generating systematic documentation framework...\n'));

    // Initialize agent
    const agent = new FiveDocumentFrameworkAgent({
      projectConfig: {
        name: path.basename(options.projectDir),
      },
      generationConfig: {
        outputDir: options.outputDir || options.projectDir,
        backupExisting: options.backupExisting,
        validateConsistency: !commands.validate || !options.validateOnly
      },
      templateDir: options.templateDir,
      outputDir: options.outputDir || options.projectDir,
      validateConsistency: true
    });

    // Set up event listeners for progress feedback
    if (options.verbose) {
      agent.on('agent:initializing', (data) => {
        console.log(chalk.blue('🔧 Initializing agent...'));
      });

      agent.on('document:generated', (data) => {
        console.log(chalk.green(`✅ Generated: ${data.documentType}`));
      });

      agent.on('generation:error', (data) => {
        console.error(chalk.red(`❌ Error: ${data.error}`));
      });
    }

    // Execute commands
    if (commands.init) {
      await initializeProject();
    } else if (commands.generate) {
      const result = await agent.generate({
        validateOnly: options.validateOnly
      });
      
      displayResults(result);
    } else if (commands.validate) {
      const result = await agent.generate({
        validateOnly: true
      });
      
      displayValidationResults(result);
    } else if (commands.status) {
      await showProjectStatus();
    }

  } catch (error: any) {
    console.error(chalk.red('\n❌ Error:'), error.message);
    if (options.verbose) {
      console.error(chalk.gray(error.stack));
    }
    process.exit(1);
  }
}

async function initializeProject() {
  console.log(chalk.blue('📁 Initializing Five Document Framework...'));
  
  const configPath = path.join(options.projectDir, '.five-document-framework.json');
  
  if (await fs.pathExists(configPath)) {
    console.log(chalk.yellow('⚠️  Configuration already exists'));
    return;
  }

  const config = {
    project: {
      name: path.basename(options.projectDir),
      version: '1.0.0',
      type: 'web',
      description: 'Generated by Five Document Framework Agent'
    },
    generation: {
      documents: {
        changelog: true,
        environmentSetup: true,
        debuggingGuide: true,
        parameterMapping: true,
        taskMasterReadme: true
      },
      validateConsistency: true,
      backupExisting: true
    }
  };

  await fs.writeJson(configPath, config, { spaces: 2 });
  console.log(chalk.green('✅ Configuration initialized'));
  console.log(chalk.blue(`📁 Config saved to: ${configPath}`));
}

async function showProjectStatus() {
  console.log(chalk.blue('📊 Project Documentation Status\n'));
  
  const documents = [
    'CHANGELOG.md',
    'ENVIRONMENT_SETUP.md', 
    'DEBUGGING_GUIDE.md',
    'PARAMETER_MAPPING.md',
    'README-task-master.md'
  ];

  for (const doc of documents) {
    const docPath = path.join(options.projectDir, doc);
    const exists = await fs.pathExists(docPath);
    
    if (exists) {
      const stats = await fs.stat(docPath);
      console.log(chalk.green('✅'), doc, chalk.gray(`(${formatFileSize(stats.size)}, ${formatDate(stats.mtime)})`));
    } else {
      console.log(chalk.red('❌'), doc, chalk.gray('(missing)'));
    }
  }
  
  console.log();
}

function displayResults(result: any) {
  console.log(chalk.blue('\n📊 Generation Results:'));
  
  if (result.success) {
    console.log(chalk.green(`✅ Successfully generated ${result.documentsGenerated.length} documents`));
    
    result.documentsGenerated.forEach((doc: any) => {
      console.log(chalk.green('  ✅'), doc.documentType, 
        chalk.gray(`(${formatFileSize(doc.size)})`));
    });
  } else {
    console.log(chalk.red(`❌ Generation failed with ${result.errors.length} errors`));
    
    result.errors.forEach((error: any) => {
      console.log(chalk.red('  ❌'), error.documentType, error.error);
    });
  }

  if (result.warnings && result.warnings.length > 0) {
    console.log(chalk.yellow(`\n⚠️  ${result.warnings.length} warnings:`));
    result.warnings.forEach((warning: string) => {
      console.log(chalk.yellow('  ⚠️ '), warning);
    });
  }

  console.log(chalk.blue(`\n⏱️  Completed in ${result.performance.totalTime}ms`));
}

function displayValidationResults(result: any) {
  console.log(chalk.blue('\n🔍 Validation Results:'));
  
  const hasErrors = result.errors && result.errors.length > 0;
  const hasWarnings = result.warnings && result.warnings.length > 0;
  
  if (!hasErrors && !hasWarnings) {
    console.log(chalk.green('✅ All documents are valid and consistent'));
  } else {
    if (hasErrors) {
      console.log(chalk.red(`❌ ${result.errors.length} validation errors:`));
      result.errors.forEach((error: any) => {
        console.log(chalk.red('  ❌'), error.message);
      });
    }
    
    if (hasWarnings) {
      console.log(chalk.yellow(`⚠️  ${result.warnings.length} validation warnings:`));
      result.warnings.forEach((warning: string) => {
        console.log(chalk.yellow('  ⚠️ '), warning);
      });
    }
  }
}

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

function formatDate(date: Date): string {
  return date.toLocaleDateString() + ' ' + date.toLocaleTimeString();
}

function showHelp() {
  console.log(chalk.blue('📚 Five Document Framework Agent - Help\n'));
  
  console.log(chalk.bold('DESCRIPTION:'));
  console.log('  Generates and maintains the 5 core documents for systematic project organization');
  console.log('  Following All-Purpose Pattern: NO hardcoded limitations, UNLIMITED scalability\n');
  
  console.log(chalk.bold('USAGE:'));
  console.log('  five-document-framework [command] [options]\n');
  
  console.log(chalk.bold('COMMANDS:'));
  console.log('  init                Initialize configuration in current project');
  console.log('  generate            Generate all documents (default)');
  console.log('  validate            Validate existing documents only');
  console.log('  status              Show current documentation status\n');
  
  console.log(chalk.bold('OPTIONS:'));
  console.log('  --project-dir <path>    Project directory (default: current directory)');
  console.log('  --output-dir <path>     Output directory for documents');
  console.log('  --template-dir <path>   Custom template directory');
  console.log('  --validate-only         Only validate, do not generate');
  console.log('  --no-backup             Skip backing up existing documents');
  console.log('  --dry-run               Show what would be generated without creating files');
  console.log('  --verbose, -v           Verbose output');
  console.log('  --help, -h              Show this help message');
  console.log('  --version               Show version information\n');
  
  console.log(chalk.bold('EXAMPLES:'));
  console.log('  five-document-framework                    # Generate all documents');
  console.log('  five-document-framework init               # Initialize configuration');
  console.log('  five-document-framework validate           # Validate existing documents');
  console.log('  five-document-framework status             # Show documentation status');
  console.log('  five-document-framework --project-dir ../other-project  # Generate for another project\n');
  
  console.log(chalk.bold('GENERATED DOCUMENTS:'));
  console.log('  • CHANGELOG.md          - Semantic versioning and change tracking');
  console.log('  • ENVIRONMENT_SETUP.md  - Complete configuration guide');
  console.log('  • DEBUGGING_GUIDE.md    - 30-minute rule and systematic debugging');
  console.log('  • PARAMETER_MAPPING.md  - Master integration reference');
  console.log('  • README-task-master.md - TaskMaster workflow documentation\n');
}

function showVersion() {
  const packagePath = path.join(__dirname, '..', 'package.json');
  try {
    const packageJson = require(packagePath);
    console.log(`Five Document Framework Agent v${packageJson.version}`);
  } catch (error) {
    console.log('Five Document Framework Agent v1.0.0');
  }
}

// Run the CLI
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(error => {
    console.error(chalk.red('❌ Fatal error:'), error.message);
    process.exit(1);
  });
}

export { FiveDocumentFrameworkAgent };